# Generated by Django 2.2.1 on 2019-05-31 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('create_thread', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_views', models.IntegerField()),
                ('replies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_views', to='blogsite.Replies')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_views', to='blogsite.Thread')),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_thread', to='blogsite.User'),
        ),
        migrations.AddField(
            model_name='replies',
            name='thread_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_replies', to='blogsite.User'),
        ),
    ]
