# Generated by Django 2.2.1 on 2019-05-31 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('location', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField()),
                ('events_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_for_events', to='events.Events')),
                ('preson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_for_person', to='events.Person')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='preson_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preson_in_event', to='events.Person'),
        ),
    ]
